# FROM node:16-alpine
# WORKDIR "/app"
# COPY ./package.json ./
# RUN npm install --legacy-peer-deps
# COPY . .

# CMD ["npm", "run", "start"]

FROM node:16-alpine as builder
WORKDIR "/app"
COPY ./package.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

#nginx
FROM nginx
COPY ./front-nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
